{
    "header":{
        "rescd":"000",
        "resmsg":"정상",
        "title":"다운로드",
        "gubun":"C"
    },
    "data":{
        "row":[
            {
                "name":"워드 2007 무작정 따라하기",
                "url":"",
                "type":"D",
                "contendid":"8385855"
            },
            {
                "name":"워크북",
                "url":"http://www.kyobo.com/wb.mp4",
                "type":"C",
                "contendid":"8385856"
            },
            {
                "name":"과제",
                "url":"http://www.kyobo.com/hw.pdf",
                "type":"C",
                "contendid":"8385857"
            },
            {
                "name":"엑셀 & 파워포인트 2007 무작정 따라하기",
                "url":"",
                "type":"D",
                "contendid":"8385858"
            },
            {
                "name":"워크북",
                "url":"http://www.kyobo.com/wb.pdf",
                "type":"C",
                "contendid":"8385859"
            }
        ]
    }
}
